name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build and deploy to Heroku
      env:
        HEROKU_API_KEY:
        HEROKU_APP_NAME:
      run: |
        npm run build
        npx heroku-cli apps:deploy
